FROM python:3.7-alpine

RUN adduser -D flask
RUN pip install virtualenv --upgrade

WORKDIR /home/flask/app

COPY . /home/flask/app
# COPY kubeconfig /home/kstatus/.kube/config
	
RUN set -e; \
	apk add --no-cache --virtual .build-deps \
		gcc \
		libc-dev \
		linux-headers \
        libffi-dev \
        openssl-dev \
	; \
	pip install -r requirements.txt; \
	apk del .build-deps;

RUN chown -R flask:flask ./
USER flask

EXPOSE 5000
ENV FLASK_APP app.py

CMD ["flask", "run", "--host=0.0.0.0"]